### ISSUE TITLE
Adafruit MacroPad RP2040 display shifted slightly left

### ISSUE THREAD

**Issue by Anomalocaridid** [adafruit/Adafruit_CircuitPython_DisplayIO_SH1106#12]
I am trying to use this library to drive the Adafruit MacroPad's SH1106 display without using the MacroPad library and it appears that whatever is drawn on the screen gets shifted slightly to the left. This problem does not occur on the CircuitPython boot screen or on code that does not rely on this library, such as the arduino-based demo code it came with or [the code from this guide](https://learn.adafruit.com/dragon-drop-a-circuitpython-game-for-macropad/overview). 

The below image shows what happens when I try to write "Hello World" at (0,0) (code at bottom). Note the extra pixels on the right edge, which I believe is part of the CircuitPython boot screen that did not get erased when the display was initialized.
![IMG_20230808_211319](https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SH1106/assets/29845794/f5299c3d-3138-4361-b321-6388c8ad8e81)

Here is a picture of the CircuitPython boot screen. The rightmost part of the "n" at the end of the second line appears to line up with the extra pixels in the above picture.
![IMG_20230808_211611](https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SH1106/assets/29845794/19548c26-6974-4ca0-8f85-fba5b3e2d0a2)

The code that I used:
```python
import busio
import board
import displayio
import terminalio
from adafruit_display_text import label
import adafruit_displayio_sh1106

displayio.release_displays()

# Use for SPI
spi = busio.SPI(board.SCK, board.MOSI)
display_bus = displayio.FourWire(
    spi,
    command=board.OLED_DC,
    chip_select=board.OLED_CS,
    reset=board.OLED_RESET,
    baudrate=1000000,
)

display = adafruit_displayio_sh1106.SH1106(display_bus, width=128, height=64)

# Make the display context
splash = displayio.Group()
display.show(splash)

# Draw a label
text = "Hello, World!"
text_area = label.Label(
    terminalio.FONT,
    text=text,
    color=0xFFFFFF,
    anchor_point=(0.0, 0.0),
    anchored_position=(0, 0),
)
splash.append(text_area)

while True:
    pass
```

**Comment by makermelissa** [comment]
The driver is built into circuitpython, so there's no need to reinitialize the screen. You should be able to just use board.DISPLAY.

**Comment by Anomalocaridid** [comment]
My bad. It works perfectly with `board.DISPLAY`. Thanks a lot!
