### ISSUE TITLE
Return of the wake/sleep issue

### ISSUE THREAD

**Issue by EAGrahamJr** [adafruit/Adafruit_CircuitPython_DisplayIO_SH1106#21]
Since I can't re-open #17, here's a new one:

```python
Traceback (most recent call last):
File "asyncio/core.py", line 261, in run_until_complete
File "code.py", line 21, in display_stuff
File "display.py", line 59, in update
File "adafruit_displayio_sh1106.py", line 118, in sleep
TypeError: object with buffer protocol required
```

`Adafruit CircuitPython 9.2.0-beta.0-25-g7f14b9c49a on 2024-10-04; Adafruit QT Py ESP32-S3 4MB Flash 2MB PSRAM with ESP32S3`

Note that this is similar to adafruit/Adafruit_CircuitPython_DisplayIO_SSD1306#47

**Comment by FoamyGuy** [comment]
Closing this, I believe it was resolved by https://github.com/adafruit/Adafruit_Blinka_Displayio/pull/142. Please re-open or create new issue if you still have this problem under latest versions.
